# ---------------------------------------------------------------------------- #
# Site Settings (站点设置)
# ---------------------------------------------------------------------------- #

title: young_fan的博客                                  # 你的博客标题
email: 3336523704@qq.com                      # 你的邮箱地址 (可选，用于某些主题)
description: >-                                   # 你的博客描述 (用于 SEO 和主题显示)
  欢迎来到我的个人博客！
baseurl: ""                                       # 如果你的博客部署在子路径 (例如 username.github.io/blog)，则设置为 "/blog"；否则留空
url: "https://autumn-night.github.io"             # 你的博客完整 URL (注意替换你的 GitHub 用户名)
github_username: autumn-night                       # 你的 GitHub 用户名 (用于链接到你的 GitHub 页面)

# ---------------------------------------------------------------------------- #
# Custom Variables (自定义变量 - 你可以在模板中访问这些变量)
# ---------------------------------------------------------------------------- #

author:   
  name: yougn_fan   
  # avatar: "/_posts/_images/young_fan.png"                 
  bio: scu23级本科                     # 你的个人简介 (可选)
  # twitter_username: your_twitter_handle          # 你的 Twitter 用户名 (可选)

# ---------------------------------------------------------------------------- #
# Build Settings (构建设置)
# ---------------------------------------------------------------------------- #

markdown: kramdown                                 # Markdown 解析器 (常用的有 kramdown 和 redcarpet)
kramdown:
  input: GFM                                       # 使用 GitHub Flavored Markdown
  syntax_highlighter: rouge                        # 代码高亮工具 (常用的有 rouge 和 highlight.js)
  syntax_highlighter_opts:                           # rouge 的配置选项 (可选)
    css_class: 'highlight'
permalink: pretty                                  # 文章链接格式 (常用的有: date, pretty, none)
exclude:                                         # 构建时排除的文件和文件夹
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
include:                                         # 构建时需要包含的文件和文件夹 (通常不需要配置)
keep_files:                                      # 构建后需要保留的文件和文件夹 (例如 .well-known)
  - .well-known

# ---------------------------------------------------------------------------- #
# Theme Settings (主题设置)
# ---------------------------------------------------------------------------- #

theme: minima                                       # 你正在使用的主题名称 (如果是 Jelly，则设置为 jelly)
# remote_theme: jekyll/minima                      # 如果你使用 GitHub 上托管的主题，可以这样指定


minima:
  date_format: "%Y年%-m月%-d日"
# ---------------------------------------------------------------------------- #
# Pagination Settings (分页设置)
# ---------------------------------------------------------------------------- #

paginate: 10                                        # 每页显示的文章数量
paginate_path: "/page:num/"                       # 分页链接的格式

# ---------------------------------------------------------------------------- #
# Collections (集合 - 用于组织不同类型的内容，例如项目、作品集等)
# ---------------------------------------------------------------------------- #

# projects:
#   output: true
#   permalink: /projects/:path/

# ---------------------------------------------------------------------------- #
# Defaults (默认设置 - 为不同类型的文件设置默认的 front matter)
# ---------------------------------------------------------------------------- #

defaults:
  - scope:
      path: ""                                     # 应用于所有文件
      type: "posts"                                # 应用于 posts 集合
    values:
      layout: "post"                               # 使用 post 布局
      author: "young_fan"                             # 默认作者
      permalink: /:year/:month/:day/:title/         # posts 的链接格式 (可以覆盖全局的 permalink)
  - scope:
      path: ""
      type: "pages"                                # 应用于 pages 集合
    values:
      layout: "page"                               # 使用 page 布局

# ---------------------------------------------------------------------------- #
# Plugins (插件设置)
# ---------------------------------------------------------------------------- #

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# ---------------------------------------------------------------------------- #
# Jelly Specific Settings (Jelly 主题特定的设置 - 根据 Jelly 的文档进行配置)
# ---------------------------------------------------------------------------- #

# Jelly 主题通常会有自己特定的配置项，例如菜单、社交链接、评论系统等。
# 你需要参考 Jelly 主题的官方文档来配置这些选项。
# 示例 (请替换为 Jelly 主题实际使用的配置项):

menu:
  - title: 首页
    url: /
  - title: 关于
    url: /about/
  - title: 归档
    url: /archive/

# analytics:
#   provider: "google"                           # 分析服务提供商 (例如 google, plausible)
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"               # 你的 Google Analytics Tracking ID

# search:
#   provider: "lunr"                             # 搜索功能提供商 (例如 lunr, algolia)

# ---------------------------------------------------------------------------- #
# Sass Settings (Sass 设置 - 如果你自定义 CSS)
# ---------------------------------------------------------------------------- #

sass:
  sass_dir: _sass
  style: compressed

# ---------------------------------------------------------------------------- #
# 其他设置 (根据你的需求添加)
# ---------------------------------------------------------------------------- #

# 例如设置高亮主题
highlighter: rouge